[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "pip install -e ."  # Instala o próprio pacote em modo editável
]

[start]
cmd = """
#!/bin/bash
source /opt/venv/bin/activate
cd /app
python -m openhands.app  # ou o caminho correto para o módulo principal
"""