[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install 'Werkzeug==2.0.1' 'Flask==2.0.1'",
  "pip install -r requirements.txt",
  "pip install ."
]

[start]
cmd = "sh -c 'source /opt/venv/bin/activate && python -m openhands'"