[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "pip install -e ."
]

[start]
cmd = "source /opt/venv/bin/activate && cd /app && python -m openhands.app"