[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "chmod +x start.sh"  # Adiciona permissão de execução ao start.sh
]

[start]
cmd = "./start.sh"